# Generated by Django 4.2.10 on 2024-05-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='uploaded_by',
        ),
    ]
