# Generated by Django 4.2.10 on 2024-09-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0004_booking_queue_queueentry_resource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end',
            new_name='end_time',
        ),
    ]
